development:
  server: "http://localhost:9296/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9296/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "2989e7c9e473754d7ba4dc3e52f30bf7d6a2fa6d068f1fd0fe63b82d823f67d0"
  signature_expiration: 3600 # one hour
